spring:
  application:
    name: product
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/springCloudDemo?characterEncoding=utf8
    username: root
    password: 123456
  jpa:
   show-sql: true

eureka:
  client:
    service-url:
       defaultZone: http://127.0.0.1:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: 127.0.0.1:8080

